Repository ArkEcosystem/deployer, pull requests merged in 2019-04, with the labels that each got.

#45 refactor: set epoch in js script
  app/app-core.sh
  packages/js-deployer/bin/deployer
Labels: Complexity: Low, Type: Bugfix

#46 fix: stop-core command required network parameter
  app/process-core.sh
Labels: Complexity: Low, Type: Bugfix

#47 refactor: postgres without sudo
  app/app-core.sh
  app/args.sh
  app/process-core.sh
Labels: Complexity: Low, Type: Refactor

#49 fix: remove unnecessary milestone option
  packages/js-deployer/bin/deployer
Labels: Complexity: Low, Type: Bugfix

#52 refactor: let core auto-detect configuration
  app/app-core.sh
  app/args.sh
  app/config-core.sh
  app/process-core.sh
  app/var.sh
  bootstrap/app.sh
  bridgechain.sh
  vagrant/setup.sh
Labels: Complexity: Low, Status: In Progress, Type: Refactor

#55 chore: clone 2.2.2 until 2.3.0 is tested
  app/app-core.sh
Labels: Complexity: Low, Type: Task
