Repository ArkEcosystem/deployer, pull requests merged in 2019-09, with the labels that each got.

#90 feat: git-use-ssh option
  README.md
  app/app-core.sh
  app/app-explorer.sh
  app/args.sh
  app/var.sh
Labels: Complexity: Low, Type: Feature

#88 feat: add update-core command to upgrade deployer chains to 2.5.19
  .github/stale.yml
  CODEOWNERS
  README.md
  app/app-core.sh
  app/update-core-relay.sh
  app/update-core.sh
  bootstrap/app.sh
  manifest.json
  packages/js-deployer/yarn.lock
Labels: Complexity: Medium

#91 chore: update bridgechains to core 2.5.24
  README.md
  app/args.sh
  app/update-core.sh
  app/var.sh
Labels: Complexity: Low, Type: Task

#86 [WIP] refactor: core 2.5 & general fixes
  app/app-core.sh
  app/config-core.sh
  app/process-core.sh
  manifest.json
  packages/js-deployer/lib/builder/genesis-block.js
Labels: Complexity: Low

#94 fix: no longer using build.js to build the explorer
  app/app-explorer.sh
Labels: Complexity: Low, Type: Bugfix

#95 chore: use core 2.5.25 when deploying bridgechains
  app/app-core.sh
  app/update-core.sh
Labels: Complexity: Low, Type: Task

#96 fix: use correct external IP on EC2 instances
  lib/utils.sh
Labels: Complexity: Low, Type: Bugfix
